In [2]:
import jax.numpy as jnp
from jax import random
import sys
sys.path.append('..')

In [3]:
from daisylm.jax_core.tokenizer import BPETokenizer

In [4]:
tokenizer = BPETokenizer()

In [27]:
len(tokenizer.encode('The ball is red'))

15

In [6]:
import numpy as np

In [24]:
vec_matrix = np.random.randn(5000, 8).astype('int32')

In [25]:
inputs = [464, 2613, 318, 2266]
vec_matrix[inputs]

array([[ 0,  0,  0, -1,  0,  0, -1,  0],
       [ 1,  0,  1,  1,  0,  0, -1,  1],
       [ 0,  0,  0,  0,  1,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]], dtype=int32)

In [26]:
pos_matrix = np.random.randn(5000, 8).astype('int32')

In [34]:
indices = [i for i in range(4)]

In [37]:
pos_matrix[indices]

array([[ 0,  0,  0,  0,  0,  1,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, -1, -1],
       [ 0,  2,  0,  1, -1,  0,  0,  0]], dtype=int32)

In [38]:
vec_matrix + pos_matrix

array([[ 0,  0,  2, ...,  1,  1,  0],
       [ 0,  0,  0, ..., -1,  0,  0],
       [ 0, -1, -1, ...,  0, -2, -1],
       ...,
       [ 1,  0, -1, ...,  0,  1,  0],
       [ 1, -1,  0, ..., -1, -1,  0],
       [-1,  0,  0, ...,  0,  0, -2]], shape=(5000, 8), dtype=int32)